/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.dashboard;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import java.awt.GridLayout;
import java.text.DecimalFormat;
import java.text.SimpleDateFormat;
import java.util.Date;

import javax.swing.BoxLayout;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.LayoutStyle.ComponentPlacement;
import java.awt.Color;
import javax.swing.border.EmptyBorder;
import javax.swing.table.DefaultTableModel;

import dto.ImportInvoice;
import dto.ImportInvoiceDetail;

import javax.swing.JLabel;
import javax.swing.SwingConstants;
import java.awt.Cursor;
import javax.swing.border.EtchedBorder;

/**
 *
 * @author Laptop K1
 */
public class ChiTietPhieuNhap extends javax.swing.JFrame {

	ImportInvoice ii;
    /**
     * Creates new form ChiTietPhieuNhap
     */
    public ChiTietPhieuNhap(ImportInvoice importInvoice) {
    	ii = importInvoice;
    	getContentPane().setPreferredSize(new Dimension(650, 630));
    	getContentPane().setBackground(new Color(240, 247, 250));
        initComponents();
        setTableData();
    }

    private void setTableData() {
		// TODO Auto-generated method stub
    	DefaultTableModel model = (DefaultTableModel) table.getModel();
		for (ImportInvoiceDetail iid : ii.getDetails()) {
			Object[] data = {
				iid.getProductId(),
				iid.prd.getProductName(),
				iid.getQuantity(),
				iid.getImportPrice()
			};
			model.addRow(data);
		}
		
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel9 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jPanel1.setBounds(3, 0, 644, 50);
        jPanel1.setFont(new Font("Tahoma", Font.PLAIN, 21));
        jPanel1.setPreferredSize(new Dimension(10, 50));
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setBounds(3, 56, 644, 79);
        jPanel2.setOpaque(false);
        jPanel4 = new javax.swing.JPanel();
        jPanel4.setOpaque(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setBounds(6, 6, 149, 17);
        jLabel2.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblMP = new JLabel(String.valueOf(ii.getImportInvoiceId()));
        lblMP.setOpaque(true);
        lblMP.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
        lblMP.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblMP.setBounds(6, 35, 149, 28);
        lblMP.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        lblMP.setHorizontalAlignment(SwingConstants.CENTER);
        lblMP.setBackground(new Color(255, 255, 255));
        jPanel5 = new javax.swing.JPanel();
        jPanel5.setOpaque(false);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setBounds(6, 6, 149, 17);
        jLabel3.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblNVN = new JLabel(ii.employee.getFullName());
        lblNVN.setOpaque(true);
        lblNVN.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
        lblNVN.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNVN.setBounds(6, 35, 149, 28);
        lblNVN.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        lblNVN.setHorizontalAlignment(SwingConstants.CENTER);
        lblNVN.setBackground(new Color(255, 255, 255));
        jPanel6 = new javax.swing.JPanel();
        jPanel6.setOpaque(false);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setBounds(6, 6, 149, 17);
        jLabel4.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblNCC = new JLabel(ii.supplier.getSupplierName());
        lblNCC.setOpaque(true);
        lblNCC.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
        lblNCC.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNCC.setBounds(6, 35, 149, 28);
        lblNCC.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        lblNCC.setHorizontalAlignment(SwingConstants.CENTER);
        lblNCC.setBackground(new Color(255, 255, 255));
        jPanel7 = new javax.swing.JPanel();
        jPanel7.setOpaque(false);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setBounds(6, 6, 149, 17);
        jLabel5.setFont(new Font("Tahoma", Font.BOLD, 14));
        lblNT = new JLabel((new SimpleDateFormat("dd/MM/yyyy")).format(ii.getInvoiceDate()));
        lblNT.setOpaque(true);
        lblNT.setBorder(new EtchedBorder(EtchedBorder.LOWERED, null, null));
        lblNT.setFont(new Font("Tahoma", Font.BOLD, 11));
        lblNT.setBounds(6, 35, 149, 28);
        lblNT.setCursor(Cursor.getPredefinedCursor(Cursor.DEFAULT_CURSOR));
        lblNT.setHorizontalAlignment(SwingConstants.CENTER);
        lblNT.setBackground(new Color(255, 255, 255));
        jPanel8 = new javax.swing.JPanel();
        jPanel8.setBounds(8, 141, 634, 438);
        jPanel8.setOpaque(false);
        jPanel8.setBorder(new EmptyBorder(0, 10, 10, 10));
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(51, 102, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN PHIẾU NHẬP");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel2.setLayout(new java.awt.GridLayout(1, 4));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        jLabel2.setText("Mã phiếu");

        jPanel2.add(jPanel4);
        jPanel4.setLayout(null);
        jPanel4.add(jLabel2);
        jPanel4.add(lblMP);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setText("Nhân viên nhập");

        jPanel2.add(jPanel5);
        jPanel5.setLayout(null);
        jPanel5.add(jLabel3);
        jPanel5.add(lblNVN);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));

        jLabel4.setText("Nhà cung cấp");

        jPanel2.add(jPanel6);
        jPanel6.setLayout(null);
        jPanel6.add(lblNCC);
        jPanel6.add(jLabel4);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));

        jLabel5.setText("Thời gian tạo");

        jPanel2.add(jPanel7);
        jPanel7.setLayout(null);
        jPanel7.add(jLabel5);
        jPanel7.add(lblNT);

        table.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        table.setModel(new DefaultTableModel(
        	new Object[][] {
        	},
        	new String[] {
        		"M\u00E3 SP", "T\u00EAn SP", "S\u1ED1 l\u01B0\u1EE3ng", "\u0110\u01A1n gi\u00E1"
        	}
        ) {
        	boolean[] columnEditables = new boolean[] {
        		false, false, false, false
        	};
        	public boolean isCellEditable(int row, int column) {
        		return columnEditables[column];
        	}
        });
        table.getColumnModel().getColumn(0).setPreferredWidth(15);
        table.getColumnModel().getColumn(1).setResizable(false);
        table.getColumnModel().getColumn(1).setPreferredWidth(260);
        table.getColumnModel().getColumn(2).setResizable(false);
        table.getColumnModel().getColumn(3).setResizable(false);
        table.setToolTipText("");
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jScrollPane1.setViewportView(table);
        jPanel1.setLayout(new GridLayout(0, 1, 0, 0));
        jPanel1.add(jLabel1);
        jPanel8.setLayout(new BoxLayout(jPanel8, BoxLayout.X_AXIS));
        jPanel8.add(jScrollPane1);
        getContentPane().setLayout(null);
        getContentPane().add(jPanel2);
        getContentPane().add(jPanel1);
        getContentPane().add(jPanel8);
        
        lblNewLabel = new JLabel("Tổng giá trị phiếu:");
        lblNewLabel.setHorizontalAlignment(SwingConstants.TRAILING);
        lblNewLabel.setFont(new Font("Tahoma", Font.BOLD, 20));
        lblNewLabel.setBounds(18, 580, 198, 33);
        getContentPane().add(lblNewLabel);
        
        lblGTP = new JLabel((new DecimalFormat("#,### VNĐ").format(ii.getTotal())));
        lblGTP.setForeground(new Color(0, 0, 0));
        lblGTP.setFont(new Font("Tahoma", Font.PLAIN, 20));
        lblGTP.setBounds(228, 580, 198, 33);
        getContentPane().add(lblGTP);

        pack();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ChiTietPhieuNhap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
//                new ChiTietPhieuNhap().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable table;
    private JLabel lblMP;
    private JLabel lblNVN;
    private JLabel lblNCC;
    private JLabel lblNT;
    private JLabel lblNewLabel;
    private JLabel lblGTP;
}
