/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package gui.dashboard;

import java.awt.Color;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import javax.swing.AbstractButton;
import org.kordamp.ikonli.materialdesign2.*;
import org.kordamp.ikonli.swing.FontIcon;
import java.awt.Dimension;
import java.awt.Font;
import javax.swing.JComboBox;
import java.awt.Cursor;

/**
 *
 * @author Hieu188
 */
public class NewJPanel extends javax.swing.JPanel {

    private static final long serialVersionUID = 1L;
	/**
     * Creates new form NewJPanel
     */
    public NewJPanel() {
		setSize(new Dimension(1150, 800));
        initComponents();
        addIcon();
        defineBtnEvent();
        setToolsEnabled(true, true, true, true, true, true, true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel = new javax.swing.JPanel();
        panel.setBorder(null);
        pnContent = new javax.swing.JPanel();
        headPanel = new javax.swing.JPanel();
        headPanel.setBorder(null);
        pnTools = new javax.swing.JPanel();
        btnAdd = new javax.swing.JButton();
        btnDel = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnImport = new javax.swing.JButton();
        btnExport = new javax.swing.JButton();
        btnDetail = new javax.swing.JButton();
        btnFilter = new javax.swing.JButton();
        pnSearch = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnSearch = new javax.swing.JButton();
        btnSearch.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        btnReload = new javax.swing.JButton();

        setBackground(new Color(240, 247, 250));
        setBorder(javax.swing.BorderFactory.createEmptyBorder(25, 25, 25, 25));
        setForeground(new java.awt.Color(240, 247, 250));
        setMinimumSize(new java.awt.Dimension(1150, 143));
        setPreferredSize(new java.awt.Dimension(1150, 800));
        setRequestFocusEnabled(false);
        setLayout(new java.awt.GridLayout(1, 0));

        panel.setOpaque(false);
        panel.setLayout(new java.awt.BorderLayout(0, 25));

        pnContent.setBackground(new Color(240, 247, 250));
        pnContent.setPreferredSize(new java.awt.Dimension(0, 0));
        pnContent.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        panel.add(pnContent, java.awt.BorderLayout.CENTER);

        headPanel.setPreferredSize(new java.awt.Dimension(1100, 90));
        headPanel.setLayout(new java.awt.GridLayout(1, 2));

        pnTools.setBackground(new Color(240, 247, 250));
        pnTools.setBorder(null);
        pnTools.setLayout(new java.awt.GridLayout(1, 7, 5, 0));

        btnAdd.setBackground(new java.awt.Color(255, 255, 255));
        btnAdd.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        btnAdd.setForeground(new java.awt.Color(0, 0, 0));
        btnAdd.setText("Thêm");
        btnAdd.setBorder(null);
        btnAdd.setBorderPainted(false);
        btnAdd.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAdd.setFocusPainted(false);
        btnAdd.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnAdd.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTools.add(btnAdd);

        btnDel.setBackground(new java.awt.Color(255, 255, 255));
        btnDel.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDel.setForeground(new java.awt.Color(0, 0, 0));
        btnDel.setText("Xóa");
        btnDel.setBorder(null);
        btnDel.setBorderPainted(false);
        btnDel.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDel.setFocusPainted(false);
        btnDel.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDel.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTools.add(btnDel);

        btnEdit.setBackground(new java.awt.Color(255, 255, 255));
        btnEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnEdit.setForeground(new java.awt.Color(0, 0, 0));
        btnEdit.setText("Sửa");
        btnEdit.setBorder(null);
        btnEdit.setBorderPainted(false);
        btnEdit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEdit.setFocusPainted(false);
        btnEdit.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnEdit.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTools.add(btnEdit);

        btnImport.setBackground(new java.awt.Color(255, 255, 255));
        btnImport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnImport.setForeground(new java.awt.Color(0, 0, 0));
        btnImport.setText("Excel");
        btnImport.setBorder(null);
        btnImport.setBorderPainted(false);
        btnImport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnImport.setFocusPainted(false);
        btnImport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnImport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTools.add(btnImport);

        btnExport.setBackground(new java.awt.Color(255, 255, 255));
        btnExport.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnExport.setForeground(new java.awt.Color(0, 0, 0));
        btnExport.setText("Xuất file");
        btnExport.setBorder(null);
        btnExport.setBorderPainted(false);
        btnExport.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnExport.setFocusPainted(false);
        btnExport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnExport.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTools.add(btnExport);

        btnDetail.setBackground(new java.awt.Color(255, 255, 255));
        btnDetail.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnDetail.setForeground(new java.awt.Color(0, 0, 0));
        btnDetail.setText("Chi tiết");
        btnDetail.setBorder(null);
        btnDetail.setBorderPainted(false);
        btnDetail.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDetail.setFocusPainted(false);
        btnDetail.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnDetail.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTools.add(btnDetail);

        btnFilter.setBackground(new java.awt.Color(255, 255, 255));
        btnFilter.setFont(new Font("Tahoma", Font.BOLD, 14)); // NOI18N
        btnFilter.setForeground(new java.awt.Color(0, 0, 0));
        btnFilter.setText("Bộ lọc");
        btnFilter.setBorder(null);
        btnFilter.setBorderPainted(false);
        btnFilter.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnFilter.setFocusPainted(false);
        btnFilter.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnFilter.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        pnTools.add(btnFilter);

        headPanel.add(pnTools);

        pnSearch.setBackground(new Color(240, 247, 250));
        pnSearch.setBorder(javax.swing.BorderFactory.createEmptyBorder(22, 1, 1, 1));
        
        comboBox = new JComboBox();
        comboBox.setBackground(new Color(255, 255, 255));
        comboBox.setPreferredSize(new Dimension(120, 30));
        pnSearch.add(comboBox);

        txtSearch.setBackground(new java.awt.Color(255, 255, 255));
        txtSearch.setFont(new java.awt.Font("Times New Roman", 2, 14)); // NOI18N
        txtSearch.setForeground(new java.awt.Color(0, 0, 0));
        txtSearch.setPreferredSize(new Dimension(200, 30));
        pnSearch.add(txtSearch);

        btnSearch.setBorder(null);
        btnSearch.setBorderPainted(false);
        btnSearch.setContentAreaFilled(false);
        btnSearch.setPreferredSize(new java.awt.Dimension(30, 30));
        pnSearch.add(btnSearch);

        btnReload.setBackground(new java.awt.Color(64, 128, 128));
        btnReload.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btnReload.setForeground(new Color(255, 255, 255));
        btnReload.setText("Làm mới");
        btnReload.setPreferredSize(new Dimension(120, 30));
        pnSearch.add(btnReload);

        headPanel.add(pnSearch);

        panel.add(headPanel, java.awt.BorderLayout.PAGE_START);

        add(panel);
    }// </editor-fold>//GEN-END:initComponents

    private void addIcon() {
            btnAdd.setIcon(FontIcon.of(MaterialDesignP.PLUS_CIRCLE, 40, Color.decode("#2ecc71")));
            btnDel.setIcon(FontIcon.of(MaterialDesignT.TRASH_CAN, 40, Color.decode("#f2b70b")));
            btnEdit.setIcon(FontIcon.of(MaterialDesignP.PEN, 40, Color.decode("#d75a4a")));
            btnImport.setIcon(FontIcon.of(MaterialDesignF.FILE_EXCEL, 40, Color.decode("#0e532e")));
            btnExport.setIcon(FontIcon.of(MaterialDesignE.EXPORT, 40, Color.decode("#147943")));
            btnDetail.setIcon(FontIcon.of(MaterialDesignI.INFORMATION_OUTLINE, 40, Color.decode("#2196f3")));
            btnFilter.setIcon(FontIcon.of(MaterialDesignF.FILTER, 40, Color.decode("#58646c")));
            btnReload.setIcon(FontIcon.of(MaterialDesignR.RELOAD, 18, btnReload.getForeground()));
            btnSearch.setIcon(FontIcon.of(MaterialDesignM.MAGNIFY, 25, Color.black));
    }
    private void makeHoverEff(AbstractButton btn) {
        Color iconColor = ((FontIcon) btn.getIcon()).getIconColor();
        Color bg = btn.getBackground();
        Color fore = btn.getForeground();
        if (!btn.isEnabled()) {
                ((FontIcon) btn.getIcon()).setIconColor(Color.decode("#999999"));
                btn.setForeground(Color.decode("#999999"));
                return;
        }
        btn.removeActionListener(null);
        btn.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseEntered(MouseEvent e) {
                if (btn.isEnabled()) {
                    btn.setBackground(Color.decode("#4b545b"));
                    btn.setForeground(Color.white);
                    ((FontIcon) btn.getIcon()).setIconColor(Color.white);
                } 
            }

            @Override
            public void mouseExited(MouseEvent e) {
                if (btn.isEnabled()) {
                        btn.setBackground(bg);
                        btn.setForeground(fore);
                        ((FontIcon) btn.getIcon()).setIconColor(iconColor);
                }
            }
        });
    }
    private void defineBtnEvent() {
        btnAdd.addActionListener(e -> { setAddEvent(); });
        btnDel.addActionListener(e -> { setDelEvent(); });
        btnEdit.addActionListener(e -> { setEditEvent(); });
        btnImport.addActionListener(e -> { setImportEvent(); });
        btnExport.addActionListener(e -> { setExportEvent(); });
        btnDetail.addActionListener(e -> { setDetailEvent(); });
        btnFilter.addActionListener(e -> { setFilterEvent(); });
    }

    //ĐỊNH NGHĨA CÁC SỰ KIỆN BẰNG CÁCH OVERRIDE NHỮNG HÀM NÀY
    protected void setAddEvent() {}
    protected void setDelEvent() {}
    protected void setEditEvent() {}
    protected void setImportEvent() {}
    protected void setExportEvent() {}
    protected void setDetailEvent() {}
    protected void setFilterEvent() {}
    protected void setSearchEvent() {}
    protected void setReloadEvent() {}


    protected void setToolsEnabled(boolean add, boolean delete, boolean edit, boolean importExcel, boolean exportExcel, boolean detail, boolean filter) {
        btnAdd.setEnabled(add);
        btnDel.setEnabled(delete);
        btnEdit.setEnabled(edit);
        btnImport.setEnabled(importExcel);
        btnExport.setEnabled(exportExcel);
        btnDetail.setEnabled(detail);
        btnFilter.setEnabled(filter);
        makeHoverEff(btnAdd);
        makeHoverEff(btnDel);
        makeHoverEff(btnEdit);
        makeHoverEff(btnImport);
        makeHoverEff(btnExport);
        makeHoverEff(btnDetail);
        makeHoverEff(btnFilter);
    }

    public NewJPanel(boolean add, boolean delete, boolean edit, boolean importExcel, boolean exportExcel, boolean detail, boolean filter) {
        this();
        setToolsEnabled(add, delete, edit, importExcel, exportExcel, detail, filter);
    }
    
    protected String getSearchContent() {
        String searchContent = txtSearch.getText();
        txtSearch.setText("");
        return searchContent;
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnDel;
    private javax.swing.JButton btnDetail;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnExport;
    private javax.swing.JButton btnFilter;
    private javax.swing.JButton btnImport;
    private javax.swing.JButton btnReload;
    protected javax.swing.JButton btnSearch;
    private javax.swing.JPanel headPanel;
    private javax.swing.JPanel panel;
    protected javax.swing.JPanel pnContent;
    private javax.swing.JPanel pnSearch;
    private javax.swing.JPanel pnTools;
    protected javax.swing.JTextField txtSearch;
    protected JComboBox comboBox;
    // End of variables declaration//GEN-END:variables
}
