/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.dashboard;

import java.util.Calendar;
import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.border.EmptyBorder;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;

/**
 *
 * @author User
 */
public class ThemNVGUI extends javax.swing.JFrame {

    /**
     * Creates new form them_nv
     */
    public ThemNVGUI() {
    	getContentPane().setBackground(new Color(240, 247, 250));
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel4.setOpaque(false);
        jButton1 = new javax.swing.JButton();
        jButton1.setFont(new Font("Tahoma", Font.BOLD, 10));
        jButton1.setBorderPainted(false);
        jButton2 = new javax.swing.JButton();
        jButton2.setFont(new Font("Tahoma", Font.BOLD, 10));
        jButton2.setBorderPainted(false);
        jPanel5 = new javax.swing.JPanel();
        jPanel5.setPreferredSize(new Dimension(400, 400));
        jPanel5.setBorder(new EmptyBorder(0, 15, 15, 15));
        jPanel5.setOpaque(false);
        jPanel2 = new javax.swing.JPanel();
        jPanel2.setOpaque(false);
        jLabel2 = new javax.swing.JLabel();
        jLabel2.setFont(new Font("SansSerif", Font.BOLD, 12));
        textFieldStaffName = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jPanel3.setOpaque(false);
        jLabel4 = new javax.swing.JLabel();
        jLabel4.setFont(new Font("SansSerif", Font.BOLD, 12));
        textFieldStaffEmail = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel6.setOpaque(false);
        jLabel5 = new javax.swing.JLabel();
        jLabel5.setFont(new Font("SansSerif", Font.BOLD, 12));
        textFieldStaffPhone = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jPanel7.setOpaque(false);
        jPanel9 = new javax.swing.JPanel();
        jPanel9.setOpaque(false);
        jLabel3 = new javax.swing.JLabel();
        jLabel3.setFont(new Font("SansSerif", Font.BOLD, 12));
        jPanel10 = new javax.swing.JPanel();
        jPanel10.setOpaque(false);
        radioButtonStaffMale = new javax.swing.JRadioButton();
        radioButtonStaffFemale = new javax.swing.JRadioButton();
        jPanel8 = new javax.swing.JPanel();
        jPanel8.setOpaque(false);
        jLabel6 = new javax.swing.JLabel();
        jLabel6.setFont(new Font("SansSerif", Font.BOLD, 12));
        jPanel11 = new javax.swing.JPanel();
        jPanel11.setOpaque(false);
        dateChooserStaffDOB = new com.toedter.calendar.JDateChooser();
        dateChooserStaffDOB.getCalendarButton().setBackground(new Color(240, 247, 250));
        dateChooserStaffDOB.setBackground(new Color(240, 247, 250));
        dateChooserStaffDOB.setOpaque(false);
        dateChooserStaffDOB.setDateFormatString("dd/MM/yyyy");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm nhân viên");

        jPanel1.setBackground(new java.awt.Color(22, 122, 198));
        jPanel1.setPreferredSize(new Dimension(70, 60));

        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÊM NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(3)
        			.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        			.addGap(3))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(4)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        getContentPane().add(jPanel1, BorderLayout.NORTH);

        jPanel4.setPreferredSize(new Dimension(300, 50));
        jPanel4.setLayout(new java.awt.GridBagLayout());

        jButton1.setBackground(new java.awt.Color(56, 159, 214));
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm người dùng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.ipadx = 9;
        gridBagConstraints.ipady = 10;
        gridBagConstraints.insets = new java.awt.Insets(0, 11, 0, 11);
        jPanel4.add(jButton1, gridBagConstraints);

        jButton2.setBackground(new java.awt.Color(219, 88, 96));
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Hủy bỏ");
        jButton2.setPreferredSize(new java.awt.Dimension(124, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        gridBagConstraints_1 = new java.awt.GridBagConstraints();
        gridBagConstraints_1.ipadx = 9;
        gridBagConstraints_1.ipady = 10;
        gridBagConstraints_1.insets = new java.awt.Insets(0, 9, 0, 9);
        jPanel4.add(jButton2, gridBagConstraints_1);

        getContentPane().add(jPanel4, BorderLayout.SOUTH);

        jPanel5.setLayout(new java.awt.GridLayout(5, 1));

        jPanel2.setLayout(new java.awt.GridLayout(2, 1));

        jLabel2.setText("Họ và tên");
        jPanel2.add(jLabel2);
        jPanel2.add(textFieldStaffName);

        jPanel5.add(jPanel2);

        jPanel3.setLayout(new java.awt.GridLayout(2, 1));

        jLabel4.setText("Emai");
        jPanel3.add(jLabel4);
        jPanel3.add(textFieldStaffEmail);

        jPanel5.add(jPanel3);

        jPanel6.setLayout(new java.awt.GridLayout(2, 1));

        jLabel5.setText("Số điện thoại");
        jPanel6.add(jLabel5);

        textFieldStaffPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldStaffPhoneActionPerformed(evt);
            }
        });
        jPanel6.add(textFieldStaffPhone);

        jPanel5.add(jPanel6);

        jPanel7.setLayout(new java.awt.GridLayout(2, 1));

        jLabel3.setText("Giới tính");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel7.add(jPanel9);

        jPanel10.setLayout(new java.awt.GridLayout(1, 2));

        buttonGroup1.add(radioButtonStaffMale);
        radioButtonStaffMale.setText("Nam");
        jPanel10.add(radioButtonStaffMale);

        buttonGroup1.add(radioButtonStaffFemale);
        radioButtonStaffFemale.setText("Nữ");
        jPanel10.add(radioButtonStaffFemale);

        jPanel7.add(jPanel10);

        jPanel5.add(jPanel7);

        jPanel8.setLayout(new java.awt.GridLayout(2, 1));

        jLabel6.setText("Ngày sinh");
        jPanel8.add(jLabel6);

        jPanel11.setLayout(new java.awt.GridLayout());
        jPanel11.add(dateChooserStaffDOB);

        jPanel8.add(jPanel11);

        jPanel5.add(jPanel8);

        getContentPane().add(jPanel5, BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldStaffPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldStaffPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldStaffPhoneActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        //Set giá trị mặc định cho Calendar là 1/1/1
        Calendar calendar = Calendar.getInstance();

        // Thiết lập ngày, tháng và năm là 0
        calendar.set(Calendar.YEAR, 1);
        calendar.set(Calendar.MONTH, 0); //Tháng được đếm từ 0
        calendar.set(Calendar.DAY_OF_MONTH, 1);
        dateChooserStaffDOB.setCalendar(calendar);
        textFieldStaffEmail.setText("");
        textFieldStaffName.setText("");
        textFieldStaffPhone.setText("");
        buttonGroup1.remove(radioButtonStaffFemale);
        buttonGroup1.remove(radioButtonStaffMale);
        radioButtonStaffFemale.setSelected(false); // Đảo ngược trạng thái của radioButtonStaffFemale
        radioButtonStaffMale.setSelected(false); 
        buttonGroup1.add(radioButtonStaffFemale);
        buttonGroup1.add(radioButtonStaffMale);
        JOptionPane.showMessageDialog(rootPane, "Thêm nhân viên thành công");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    	this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNVGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNVGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private com.toedter.calendar.JDateChooser dateChooserStaffDOB;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JRadioButton radioButtonStaffFemale;
    private javax.swing.JRadioButton radioButtonStaffMale;
    private javax.swing.JTextField textFieldStaffEmail;
    private javax.swing.JTextField textFieldStaffName;
    private javax.swing.JTextField textFieldStaffPhone;
    private GridBagConstraints gridBagConstraints_1;
    // End of variables declaration//GEN-END:variables
}
