/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package gui.dashboard;

import java.util.Calendar;
import java.util.Date;

import javax.swing.JOptionPane;
import java.awt.Font;
import java.awt.BorderLayout;
import java.awt.Color;
import javax.swing.border.EmptyBorder;
import java.awt.Dimension;
import java.awt.GridBagConstraints;
import javax.swing.GroupLayout.Alignment;
import javax.swing.GroupLayout;
import javax.swing.JPanel;
import java.awt.GridLayout;
import javax.swing.JLabel;
import javax.swing.JTextField;
import javax.swing.JRadioButton;
import com.toedter.calendar.JDateChooser;

import bll.AccountBLL;
import bll.CustomerBLL;
import bll.EmployeeBLL;
import dao.AccountDAO;
import dao.EmployeeDAO;
import dto.Account;
import dto.Customer;
import dto.Employee;
import system.ConfigPRJ;

import java.awt.CardLayout;
import javax.swing.JButton;
import java.awt.Insets;
import java.text.SimpleDateFormat;

import javax.swing.JToggleButton;
import java.awt.GridBagLayout;
import javax.swing.SwingConstants;
import javax.swing.JComboBox;
import javax.swing.ButtonGroup;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author User
 */
public class ThongTinNV extends javax.swing.JFrame {
	
	
	private CardLayout clayout = new CardLayout(0, 0);
	private Employee nv;
	private Account acc;


    /**
     * Creates new form them_nv
     */
    public ThongTinNV(int d) {
    	this.nv = EmployeeDAO.getInstance().readByID(d);
    	this.acc = AccountDAO.getInstance().readByID(nv.getAccountId());
    	getContentPane().setBackground(new Color(240, 247, 250));
        initComponents();
        setEvent();
        loadInfo();
    }

    private void loadInfo() {
    	txtName.setText(nv.getFullName());
    	txtDOB.setText((new SimpleDateFormat("dd/MM/yyyy")).format(nv.getDateOfBirth()));
    	txtPhone.setText(nv.getPhoneNumber());
    	txtGender.setText(nv.getGender());
    	txtAdress.setText(nv.getAddress());
    	txtUsername.setText(acc.getUsername());
    	txtPasswd.setText(acc.getPassword());
    	if (!acc.getRoleId().equals("ADM")) {
    		cbbRole.setSelectedItem(acc.getRoleId());
    	}
    	if (acc.getAccountStatus().equals("active")) {
    		cbbStatus.setSelectedIndex(0);
    	} else {
    		cbbStatus.setSelectedIndex(1);
    	}
	}

	private void setEvent() {
		// TODO Auto-generated method stub
		btnTK.addActionListener(e -> {
			clayout.show(jPanel5, "account");
		});
		btnTT.addActionListener(e -> {
			clayout.show(jPanel5, "info");
		});
		btnTK.doClick();
		btnAddE.addActionListener(e -> {
			if (acc.getRoleId().equals("ADM")) {
				JOptionPane.showMessageDialog(null, "Không thể đổi thông của người quản trị", "Thông báo", JOptionPane.ERROR_MESSAGE);
			} else {
				AccountBLL.changeRole(nv, (String) cbbRole.getSelectedItem());
	    		if (cbbStatus.getSelectedIndex() == 0) {
	    			AccountDAO.getInstance().recovery(acc.getId());
	    		} else {
	    			AccountDAO.getInstance().delete(acc.getId());
	    		}
				((EmployeesGUI) ConfigPRJ.menu.get("EMPLOYEES")).reloadTable();
				dispose();
			}
			
		});
	}

	/**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel4.setBorder(new EmptyBorder(10, 10, 10, 10));
        jPanel4.setOpaque(false);
        btnTK = new JToggleButton();
        buttonGroup.add(btnTK);
        btnTK.setFont(new Font("Tahoma", Font.BOLD, 10));
        btnTK.setBorderPainted(false);
        btnAddE = new javax.swing.JButton();
        btnAddE.setFont(new Font("Tahoma", Font.BOLD, 10));
        btnAddE.setBorderPainted(false);
        jPanel5 = new javax.swing.JPanel();
        jPanel5.setPreferredSize(new Dimension(400, 400));
        jPanel5.setOpaque(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Thêm nhân viên");

        jPanel1.setBackground(new java.awt.Color(22, 122, 198));
        jPanel1.setPreferredSize(new Dimension(70, 60));

        jLabel1.setFont(new Font("Segoe UI", Font.BOLD, 20)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("THÔNG TIN NHÂN VIÊN");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1Layout.setHorizontalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(3)
        			.addComponent(jLabel1, GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        			.addGap(3))
        );
        jPanel1Layout.setVerticalGroup(
        	jPanel1Layout.createParallelGroup(Alignment.LEADING)
        		.addGroup(jPanel1Layout.createSequentialGroup()
        			.addGap(4)
        			.addComponent(jLabel1, GroupLayout.PREFERRED_SIZE, 52, GroupLayout.PREFERRED_SIZE)
        			.addContainerGap(GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1.setLayout(jPanel1Layout);

        getContentPane().add(jPanel1, BorderLayout.NORTH);

        jPanel4.setPreferredSize(new Dimension(300, 50));

        btnTK.setBackground(new java.awt.Color(56, 159, 214));
        btnTK.setForeground(new java.awt.Color(255, 255, 255));
        btnTK.setText("Tài khoản");
        jPanel4.setLayout(new GridLayout(0, 3, 15, 0));
        jPanel4.add(btnTK);

        btnAddE.setBackground(new java.awt.Color(219, 88, 96));
        btnAddE.setForeground(new java.awt.Color(255, 255, 255));
        btnAddE.setText("Thay đổi");
        btnAddE.setPreferredSize(new java.awt.Dimension(124, 23));

        
        btnTT = new JToggleButton();
        buttonGroup.add(btnTT);
        btnTT.setText("Thông tin");
        btnTT.setForeground(Color.WHITE);
        btnTT.setFont(new Font("Tahoma", Font.BOLD, 10));
        btnTT.setBorderPainted(false);
        btnTT.setBackground(new Color(56, 159, 214));
        jPanel4.add(btnTT);
        jPanel4.add(btnAddE);

        getContentPane().add(jPanel4, BorderLayout.SOUTH);

        getContentPane().add(jPanel5, BorderLayout.CENTER);
        jPanel5.setLayout(clayout);
        
        panel = new JPanel();
        panel.setOpaque(false);
        jPanel5.add(panel, "info");
        
        jPanel5_1 = new JPanel();
        jPanel5_1.setPreferredSize(new Dimension(400, 400));
        jPanel5_1.setOpaque(false);
        jPanel5_1.setBorder(new EmptyBorder(0, 15, 15, 15));
        panel.add(jPanel5_1);
        jPanel5_1.setLayout(new GridLayout(5, 1));
        
        jPanel2 = new JPanel();
        jPanel2.setOpaque(false);
        jPanel5_1.add(jPanel2);
        jPanel2.setLayout(new GridLayout(2, 1));
        
        jLabel2 = new JLabel();
        jLabel2.setText("Họ và tên");
        jLabel2.setFont(new Font("SansSerif", Font.BOLD, 12));
        jPanel2.add(jLabel2);
        
        txtName = new JLabel();
        jPanel2.add(txtName);
        
        jPanel6 = new JPanel();
        jPanel6.setOpaque(false);
        jPanel5_1.add(jPanel6);
        jPanel6.setLayout(new GridLayout(2, 1));
        
        jLabel5 = new JLabel();
        jLabel5.setText("Số điện thoại");
        jLabel5.setFont(new Font("SansSerif", Font.BOLD, 12));
        jPanel6.add(jLabel5);
        
        txtPhone = new JLabel();
        jPanel6.add(txtPhone);
        
        jPanel7 = new JPanel();
        jPanel7.setOpaque(false);
        jPanel5_1.add(jPanel7);
        jPanel7.setLayout(new GridLayout(2, 1));
        
        jPanel9 = new JPanel();
        jPanel9.setOpaque(false);
        jPanel7.add(jPanel9);
        
        jLabel3 = new JLabel();
        jLabel3.setText("Giới tính");
        jLabel3.setFont(new Font("SansSerif", Font.BOLD, 12));
        GroupLayout gl_jPanel9 = new GroupLayout(jPanel9);
        gl_jPanel9.setHorizontalGroup(
        	gl_jPanel9.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 370, Short.MAX_VALUE)
        		.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
        );
        gl_jPanel9.setVerticalGroup(
        	gl_jPanel9.createParallelGroup(Alignment.LEADING)
        		.addGap(0, 38, Short.MAX_VALUE)
        		.addComponent(jLabel3, GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE)
        );
        jPanel9.setLayout(gl_jPanel9);
        
        jPanel10 = new JPanel();
        jPanel10.setOpaque(false);
        jPanel7.add(jPanel10);
        jPanel10.setLayout(new GridLayout(1, 2));
        
        txtGender = new JLabel();
        jPanel10.add(txtGender);
        
        jPanel8 = new JPanel();
        jPanel8.setOpaque(false);
        jPanel5_1.add(jPanel8);
        jPanel8.setLayout(new GridLayout(2, 1));
        
        jLabel6 = new JLabel();
        jLabel6.setText("Ngày sinh");
        jLabel6.setFont(new Font("SansSerif", Font.BOLD, 12));
        jPanel8.add(jLabel6);
        
        jPanel11 = new JPanel();
        jPanel11.setOpaque(false);
        jPanel8.add(jPanel11);
        jPanel11.setLayout(new GridLayout());
        
        txtDOB = new JLabel();
        jPanel11.add(txtDOB);
        
        jPanel3 = new JPanel();
        jPanel3.setOpaque(false);
        jPanel5_1.add(jPanel3);
        jPanel3.setLayout(new GridLayout(2, 1));
        
        lblaCh = new JLabel();
        lblaCh.setText("Địa chỉ");
        lblaCh.setFont(new Font("SansSerif", Font.BOLD, 12));
        jPanel3.add(lblaCh);
        
        txtAdress = new JLabel();
        jPanel3.add(txtAdress);
        
        panel_1 = new JPanel();
        panel_1.setOpaque(false);
        jPanel5.add(panel_1, "account");
        panel_1.setLayout(new GridLayout(4, 0, 0, 0));
        
        panel_3 = new JPanel();
        panel_3.setBorder(new EmptyBorder(0, 15, 0, 15));
        panel_3.setOpaque(false);
        panel_1.add(panel_3);
        panel_3.setLayout(new GridLayout(2, 0, 0, 0));
        
        jLabel2_1 = new JLabel();
        jLabel2_1.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel2_1.setText("Tên người dùng");
        jLabel2_1.setFont(new Font("SansSerif", Font.BOLD, 12));
        panel_3.add(jLabel2_1);
        
        panel_4 = new JPanel();
        panel_4.setBorder(new EmptyBorder(0, 0, 15, 0));
        panel_4.setOpaque(false);
        panel_3.add(panel_4);
        panel_4.setLayout(new GridLayout(0, 1, 0, 0));
        
        txtUsername = new JLabel();
        panel_4.add(txtUsername);
        
        panel_2 = new JPanel();
        panel_2.setOpaque(false);
        panel_2.setBorder(new EmptyBorder(0, 15, 0, 15));
        panel_1.add(panel_2);
        panel_2.setLayout(new GridLayout(2, 0, 0, 0));
        
        jLabel2_2 = new JLabel();
        jLabel2_2.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel2_2.setText("Mật khẩu");
        jLabel2_2.setFont(new Font("SansSerif", Font.BOLD, 12));
        panel_2.add(jLabel2_2);
        
        panel_7 = new JPanel();
        panel_7.setOpaque(false);
        panel_7.setBorder(new EmptyBorder(0, 0, 15, 0));
        panel_2.add(panel_7);
        panel_7.setLayout(new GridLayout(0, 1, 0, 0));
        
        txtPasswd = new JLabel();
        panel_7.add(txtPasswd);
        
        panel_5 = new JPanel();
        panel_5.setOpaque(false);
        panel_5.setBorder(new EmptyBorder(0, 15, 0, 15));
        panel_1.add(panel_5);
        panel_5.setLayout(new GridLayout(2, 0, 0, 0));
        
        jLabel2_3 = new JLabel();
        jLabel2_3.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel2_3.setText("Vai trò");
        jLabel2_3.setFont(new Font("SansSerif", Font.BOLD, 12));
        panel_5.add(jLabel2_3);
        
        panel_6 = new JPanel();
        panel_6.setOpaque(false);
        panel_6.setBorder(new EmptyBorder(0, 0, 15, 0));
        panel_5.add(panel_6);
        panel_6.setLayout(new GridLayout(0, 1, 0, 0));
        
        cbbRole = new JComboBox<String>();
        cbbRole.setModel(new DefaultComboBoxModel<String>(new String[] {"WHM", "SLR"}));
        cbbRole.setBackground(new Color(255, 255, 255));
        panel_6.add(cbbRole);
        
        panel_8 = new JPanel();
        panel_8.setOpaque(false);
        panel_8.setBorder(new EmptyBorder(0, 15, 0, 15));
        panel_1.add(panel_8);
        panel_8.setLayout(new GridLayout(2, 0, 0, 0));
        
        jLabel2_4 = new JLabel();
        jLabel2_4.setVerticalAlignment(SwingConstants.BOTTOM);
        jLabel2_4.setText("Trạng thái");
        jLabel2_4.setFont(new Font("SansSerif", Font.BOLD, 12));
        panel_8.add(jLabel2_4);
        
        panel_9 = new JPanel();
        panel_9.setOpaque(false);
        panel_9.setBorder(new EmptyBorder(0, 0, 15, 0));
        panel_8.add(panel_9);
        panel_9.setLayout(new GridLayout(0, 1, 0, 0));
        
        cbbStatus = new JComboBox<String>();
        cbbStatus.setModel(new DefaultComboBoxModel(new String[] {"Đang hoạt động", "Ngưng hoạt động"}));
        cbbStatus.setBackground(Color.WHITE);
        panel_9.add(cbbStatus);

        pack();
        
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongTinNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongTinNV(2).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private JToggleButton btnTK;
    private javax.swing.JButton btnAddE;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private JPanel panel;
    private JPanel panel_1;
    private JPanel jPanel5_1;
    private JPanel jPanel2;
    private JLabel jLabel2;
    private JLabel txtName;
    private JPanel jPanel6;
    private JLabel jLabel5;
    private JLabel txtPhone;
    private JPanel jPanel7;
    private JPanel jPanel9;
    private JLabel jLabel3;
    private JPanel jPanel10;
    private JPanel jPanel8;
    private JLabel jLabel6;
    private JPanel jPanel11;
    private JToggleButton btnTT;
    private JPanel panel_3;
    private JLabel jLabel2_1;
    private JPanel panel_4;
    private JLabel txtUsername;
    private JPanel panel_5;
    private JLabel jLabel2_3;
    private JPanel panel_6;
    private JPanel panel_2;
    private JLabel jLabel2_2;
    private JPanel panel_7;
    private JLabel txtPasswd;
    private JComboBox<String> cbbRole;
    private final ButtonGroup buttonGroup = new ButtonGroup();
    private JPanel jPanel3;
    private JLabel lblaCh;
    private JLabel txtAdress;
    private JLabel txtGender;
    private JLabel txtDOB;
    private JPanel panel_8;
    private JLabel jLabel2_4;
    private JPanel panel_9;
    private JComboBox<String> cbbStatus;
}
